title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Rayane Souissi
github_username: rayanesouuuu1234
github_repo: "tri2"
baseurl: "/tri2"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/tri2"}
    - { platform: github, user_url: "https://github.com/rayanesouuuu1234"}
    - { platform: github, user_url: "https://github.com/rayanesouuuu1234"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
